[package]
name = "tss"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
image = "0.25.5"
ril = { version = "0.10.3", features = ["png"] }
turing-smart-screen = "1.0.0"
